### ISSUE TITLE
CI fails because of weird sass behavior

### ISSUE THREAD

**Issue by ttben** [PETILLON-Sebastien/facteurs_charge#15]
https://discourse.gohugo.io/t/postcss-error-building-site-since-yesterday/25513
https://github.com/gohugoio/hugo/issues/7278
https://github.com/gohugoio/hugo/issues/7253

This may be solved by specifying node version < `10.3`

**Comment by PETILLON-Sebastien** [comment]
As you told me today, that was a temporaray problem, which is not specific to this project.
