### ISSUE TITLE
Defining API in swagger (its content must be another discussion/issue)

### ISSUE THREAD

**Issue by ttben** [PETILLON-Sebastien/facteurs_charge#22]

**Comment by PETILLON-Sebastien** [comment]
I've been doing this first draft of the API, following what we previously discussed.
[API V1](https://github.com/PETILLON-Sebastien/facteurs_charge/blob/feature/api/api.yml)

A precision I couldn't give in the YAML file :
A region ID will be in the format `CC-RR`
- CC is the country in the [ISO_3166-1 format](https://fr.wikipedia.org/wiki/ISO_3166-1)
- RR is the optional region (only if the country is France) in the [INSEE format](https://fr.wikipedia.org/wiki/Codes_g%C3%A9ographiques_de_la_France)

Example : `FR-11`, `DE`


Feel free to give your feedback. We need to validate it before we start implementing.

**Comment by ttben** [comment]
Nice!

A few questions:

- What is a `valueFilter`? If it is like "lowest, highest" it should be a pattern IMO.
- I think `unit` should be another thing than a `string`. Since we are dealing with `w`, unit can be `mw | w | MW | GW` right?
- Typo [here](https://github.com/PETILLON-Sebastien/facteurs_charge/blob/feature/api/api.yml#L297) on `hydaulic`.
- Maybe we should add `production` since we added `consumption`. It would be a high-level view of the production of a zone (without a breakdown)
- I am surprised that `zone/:id` [returns an array](https://github.com/PETILLON-Sebastien/facteurs_charge/blob/feature/api/api.yml#L154)
- I am surprised that `zones/:id` returns... nothing more?! I would have expected all the informations about a specific zone.

Otherwise: Nooiice.

**Comment by PETILLON-Sebastien** [comment]
A few responses :
- Yeah, forgot it in a copy-paste from the loadFilter =D
- I think we'll only deal with with MW, but we should restrict this to what you've listed
- Yes typo
- It seems strange without it, but what's the added value ?
- That's a mistake. I should have removed the array for a single item
- What do you want from it ? Maybe that's a sign we should delete this route ?

**Comment by PETILLON-Sebastien** [comment]
I applied your [feedback](https://github.com/PETILLON-Sebastien/facteurs_charge/blob/feature/api/api.yml) !
If you're OK with it, we close this one and open another one for the implementation.

**Comment by ttben** [comment]
I think we just need a tiny addition.

The route `production` should be plural, and returns the repartition of the production for the given zone. :)

Like, going from

```
[
  {
    "timestamp": "2020-05-26T12:19:12.853Z",
    "zoneId": "string",
    "production": {
      "value": 0,
      "unit": "string"
    }
  }
]
```

to

```
[
  {
    "timestamp": "2020-05-26T12:19:12.853Z",
    "zoneId": "string",
    "production": {
      "solar": {
         "value": 0,
         "unit": "string"
       }
    }
  }
]
```


It is actually the `breakdown` of the `production` so you can either modify the existing route, or adding a new one `production/breakdown` :) 

I'll vote for the second one!

**Comment by ttben** [comment]
Even worse,  I don't know what the API will result once the `from` and `to` filter are passed.
Any idea?

Maybe `productions?zoneid=x` will return a 24h-dataframe ? The last recorded data?

**Comment by ttben** [comment]
Actual stubs can be found here

- [`productions`](https://github.com/PETILLON-Sebastien/facteurs_charge/blob/6902c8200e28e3c3e0ac1c6352aba62f7d9bff2e/static/js/slides/power-sources-breakdown/components/SlidePowerSources.jsx#L37)
- [`loads`](https://github.com/PETILLON-Sebastien/facteurs_charge/blob/6902c8200e28e3c3e0ac1c6352aba62f7d9bff2e/static/js/slides/load-breakdown/components/SlideLoad.jsx#L22)
- [`breakdowns`](https://github.com/PETILLON-Sebastien/facteurs_charge/blob/6902c8200e28e3c3e0ac1c6352aba62f7d9bff2e/static/js/slides/load-breakdown/components/SlideLoad.jsx#L23)

What do you think?

**Comment by PETILLON-Sebastien** [comment]
OK. After a long discussion yesterday, we agreed on a full rework of the `breakdown` part of the API.
The others routes just go under `zone` as the main route (this makes me think, wow, if there is a single top ressource, isn't it a problem agaaaain ?).

I won't speak for hours, can you give me your feedback on this brand new [API](https://github.com/PETILLON-Sebastien/facteurs_charge/blob/feature/api/api.yml) ?

**Comment by ttben** [comment]
Great :)

Not sure to understand what is `stepStorage` under consumption

The following routes return the wrong field (`power` instead of `capacity`)
- `​/zones​/{zoneId}​/installations​/capacity​/{installationType}`
- `/zones/{zoneId}/installations/capacity/breakdown`  
- `/zones/{zoneId}/installations/capacity`

Other than that, it seems super-duper cool :) Congrats! Thats a damn cute baby!

**Comment by PETILLON-Sebastien** [comment]
> Not sure to understand what is stepStorage under consumption

Step storage is the use of electricity to fill back the dam.
So I made the choice to put it in the consumption part, instead of negative in the production. Do you have a better idea ? We can debate this.

> The following routes return the wrong field

The `power` field can be used for `capacity` or `production`, as they share the same fields. We can change that for readability purpose, if you prefer.

> Other than that, it seems super-duper cool :) Congrats! Thats a damn cute baby!

Yeah, pretty happy with that, looks like we finally converged (is that even a real word ?).
Maybe we'll find some mistakes, because this description is SO BIG.

**Comment by ttben** [comment]
It is not big.

It is detailed. :P

And yes converged is a word!

**Comment by PETILLON-Sebastien** [comment]
We now have a proper description.
I close the issue and open a looooot of others.
