### ISSUE TITLE
Daemon for data retrieval

### ISSUE THREAD

**Issue by PETILLON-Sebastien** [PETILLON-Sebastien/facteurs_charge#30]
Write the nodejs tool which will be launched as a background task to periodically call opendatareseaux's API and store in our specific format.
This format will be discussed here.

See `branch` [feature/30](https://github.com/PETILLON-Sebastien/facteurs_charge/tree/feature/30)

**Comment by PETILLON-Sebastien** [comment]
First, I'm currently focused on a daily-based file storage.
But there could be different approachs :
- 3 files a day
    - Production named `YYYY_MM_DD-production.json`
    - Consumption named `YYYY_MM_DD-consumption.json`
    - Exchanges named `YYYY_MM_DD-exchanges.json`
- Single file with three object from the categories described in the previous point

The first approach could be smarter if we align routes with their associated files (my favorite).
The second would be easier I think.

What's your opinion on this ?

**Comment by ttben** [comment]
I think that no matter how we split these files, we are still facing the same issues.

If we go for a one-file option, each time someone open the website, the very specific file for `today` will be opened.
If we go for a three-files option, each time someone open the website, 3 files are opened.

This can be mitigated as follow:

maintaining a 7-days window of data in-memory?

Anyway, I have no specific opinion on this.

(note: please, mention me if you need my input on something 😄  )

**Comment by PETILLON-Sebastien** [comment]
I'll make a quick summary on what has been done on this issue.

A lot of utils files have been developped, and the cron is extremely simple.
In the end we produce 3 files (as described in this discussion). The format is not exactly the same as the API in order to optimize a little the used storage.
A single day takes about 900Ko, it means ~ 330Mo a year.
So, from 2013 to today, it would be about 2.4Go. OVH currently allows me 10Go. So we need to talk about this limitation before 2040 😄 

So for now we have the cron for the past day.
I need to work on the deamon which will retrieve the data in memory.

**Comment by ttben** [comment]
Super nice!

Quick feedback as I am seeing this
[This](https://github.com/PETILLON-Sebastien/facteurs_charge/blob/658be3aa66d67e2276d8ef89fa8c779ec5dab8e8/server/daemons/store_previous_day.js#L12) wont work on non-windows os (so 98% of servers).  Use [this](https://nodejs.org/api/path.html#path_path_sep) instead ;)

That sounds nice!

>A single day takes about 900Ko, it means ~ 330Mo a year.

We can discuss optimization afterward if you want ;) It would be a challenge to do so 👍 

> I need to work on the deamon which will retrieve the data in memory.

Why a daemon would be needed to put data in memory? 🤔

**Comment by PETILLON-Sebastien** [comment]
I made the correction on the path.
I managed to launch the deamon with a simple `npm start`, and later, the server will be started within the same command.
I think this issue is finished, time to work on server and data loading.
