### ISSUE TITLE
Getting load breakdown of whole FRANCE is a corner case

### ISSUE THREAD

**Issue by ttben** [PETILLON-Sebastien/facteurs_charge#54]
When hitting `http://localhost:8080/api/v1/zones/FR/installations/breakdown` the breakdown is plainly wrong: 

```
"breakdown": {
      "solar": {
        "production": {
          "unit": "MW",
          "value": 0
        },
        "capacity": {
          "unit": "MW",
          "value": null
        }
      },
```

But getting this on a zone returns the proper schema.

**Comment by PETILLON-Sebastien** [comment]
Fixed with https://github.com/PETILLON-Sebastien/facteurs_charge/commit/970281bd6ce6986249b0869bd78b2ac85297f94e
But forgot to mention the issue
