### ISSUE TITLE
/zones/FR-11/installations/production/breakdown return production field instead of power

### ISSUE THREAD

**Issue by ttben** [PETILLON-Sebastien/facteurs_charge#60]
https://github.com/PETILLON-Sebastien/facteurs_charge/blob/epic/backend_v2/server/api/api.yml#L1142

**Comment by PETILLON-Sebastien** [comment]
Fixed with https://github.com/PETILLON-Sebastien/facteurs_charge/commit/aa0c6a6159a72a0eff65184bbb6f4f7a1f6bb066
But forgot to mention the issue
